#!/bin/bash
# Rank XI deploy to Cloudflare Pages (canonical). This script does not touch
# git: the cache-bust token is minted here and stamped into the staged tree
# only, so a deploy no longer produces a commit to push.
set -e
cd "$(dirname "$0")"

# Deploy target. Default is production (the master branch alias). `--preview`
# ships the identical staged tree to a branch alias instead, so a change can be
# opened and read as a real page before it reaches www.rankedxi.com.
#   ./deploy.sh                      -> production
#   ./deploy.sh --preview            -> preview on the current git branch
#   ./deploy.sh --preview my-branch  -> preview on a named branch
DEPLOY_BRANCH="master"
if [ "${1:-}" = "--preview" ]; then
  DEPLOY_BRANCH="${2:-$(git rev-parse --abbrev-ref HEAD)}"
  if [ "$DEPLOY_BRANCH" = "master" ]; then
    echo "refusing: --preview on master is just a production deploy" >&2; exit 1
  fi
fi
# Cloudflare Pages builds a branch alias by lowercasing, replacing every
# non-alphanumeric run with a dash, and truncating to 28 characters.
ALIAS=$(printf '%s' "$DEPLOY_BRANCH" | tr '[:upper:]' '[:lower:]' \
        | sed 's/[^a-z0-9]\{1,\}/-/g; s/^-//; s/-$//' | cut -c1-28)
if [ "$DEPLOY_BRANCH" = "master" ]; then
  LIVE="https://rank-xi.pages.dev"
else
  LIVE="https://${ALIAS}.rank-xi.pages.dev"
fi

# Mint the cache-bust token. It is stamped into the staged tree further down
# and never written back to the repo (scripts/cachebust.py). A token that is
# never committed cannot collide between branches, cannot be walked backwards
# by a merge, and cannot leave a PR red just for being a few hours old.
NEWV=$(python3 scripts/cachebust.py --mint)

# regenerate the static SEO surface from current data: the two hand-tuned
# league landing pages, per-club share cards (og/ — must run before club pages
# so they can point og:image at the cards), then the generated hub-and-leaf
# tree (club/, league/, state/) and the full sitemap that indexes it
python3 scripts/gen_seo_pages.py
python3 scripts/gen_og_cards.py
python3 scripts/gen_club_pages.py

python3 scripts/preflight.py

# Ship a staged tree, not the repo root. `wrangler pages deploy .` uploaded the
# scrapers and every raw scrape dump — including per-player names and birth years
# that the app never fetches — to public URLs. Only runtime assets go out.
# Stage path is fixed (not mktemp): wrangler.toml's pages_build_output_dir must
# name it so deploys pick up the functions/ dir and the D1 signups binding.
# The IndexNow key lives in gen_club_pages.py, which writes both the payload
# and the key file; read it back rather than keeping a second copy in sync.
INDEXNOW_KEY=$(python3 -c "import re;print(re.search(r\"INDEXNOW_KEY = '(\\w+)'\", open('scripts/gen_club_pages.py').read()).group(1))")

STAGE=".deploy-stage"
rm -rf "$STAGE"; mkdir -p "$STAGE"
trap 'rm -rf "$STAGE"' EXIT

# 404.html must ship: its presence is what turns off the Pages SPA fallback,
# so bad URLs return a real 404 instead of the homepage with HTTP 200
cp -R app.html index.html 404.html npsl-rankings.html upsl-rankings.html \
      methodology.html privacy.html player-simulator.html shots.html radar.html \
      about.html faq.html terms.html us-soccer-pyramid.html \
      club league state .well-known \
      manifest.webmanifest sw.js robots.txt llms.txt _headers _redirects \
      js css crests fonts \
      favicon.ico icon-192.png icon-512.png apple-touch-icon.png og.png google-play-badge.png "$STAGE/"
# sitemap.xml is now an index; its children are generated alongside it and are
# useless without each other. Globbed so a new club chunk (every 2,000 rated
# clubs) ships without anyone remembering to edit this line.
cp sitemap.xml sitemap-*.xml "$STAGE/"
# IndexNow key file must be fetchable at the domain root or every submission is
# rejected. Generated by gen_club_pages.py next to the payload it authenticates.
cp "$INDEXNOW_KEY".txt "$STAGE/" 2>/dev/null || true
# per-club share cards (skipped gracefully when gen_og_cards had no Pillow)
if [ -d og ]; then cp -R og "$STAGE/"; rm -f "$STAGE/og/.cards.json"; fi
# local editor/backup droppings must not reach production
find "$STAGE/js" "$STAGE/css" \( -name '*.bak' -o -name '*.tmp' \) -delete

# The one place a real cache-bust token exists. Every page and js module ships
# with the placeholder swapped for $NEWV; the repo keeps the placeholder. This
# aborts if the placeholder is missing, which would ship a build that returning
# browsers never refetch (/js/*, /css/* and /data/* are immutable for a year).
python3 scripts/cachebust.py --stamp "$STAGE" "$NEWV"

# only the data files app.js actually fetches
mkdir -p "$STAGE/data"
for f in $(grep -ohE "(fetch|grab)\('data/[a-z0-9_.-]+" js/app.js | sed "s/.*'//" | sort -u); do
  cp "$f" "$STAGE/data/"
done

echo "staged $(find "$STAGE" -type f | wc -l | tr -d ' ') files ($(du -sh "$STAGE" | cut -f1))"
# No directory arg: wrangler.toml supplies project name, output dir, functions/,
# and the D1 signups binding (bindings only apply when deploying via config).
npx -y wrangler@4.114.0 pages deploy --branch="$DEPLOY_BRANCH" --commit-dirty=true
echo "Deployed to branch $DEPLOY_BRANCH: $LIVE"

# Post-deploy gate: a deploy that ships but serves 404s must fail loudly —
# the wire JSONs were 404 in production for days (staging grep missed grab()
# fetches) and nothing noticed. Verify against the project domain (custom
# domain adds redirects + edge cache); retry to ride out propagation lag.
# In the scheduled Action a non-zero exit here files the failure issue.
verify_url() {
  for i in 1 2 3 4 5; do
    curl -sfo /dev/null "$1" && return 0
    sleep 3
  done
  echo "DEPLOY VERIFY FAILED: $1" >&2
  return 1
}
# /app.html 308s to /app, an un-tokened URL the edge caches — a check fired
# right after "Deployment complete" can still see the previous build, so this
# gets the same retry window the data files do (2026-08-18 false alarm).
verify_token() {
  for i in 1 2 3 4 5; do
    curl -sfL "$LIVE/app.html" | grep -q "$NEWV" && return 0
    sleep 3
  done
  echo "DEPLOY VERIFY FAILED: live app.html is not serving v$NEWV" >&2
  return 1
}
# A Function route or a standalone page can 404 in production while every
# tokened asset is fine — that is exactly how the wire JSONs went missing.
# /api/shots is asserted via its no-league 400 rather than a real query: the
# route must exist, but a green deploy must not depend on ASA's uptime.
verify_status() {
  for i in 1 2 3 4 5; do
    [ "$(curl -so /dev/null -w '%{http_code}' "$1")" = "$2" ] && return 0
    sleep 3
  done
  echo "DEPLOY VERIFY FAILED: $1 did not return $2" >&2
  return 1
}
vfail=0
verify_token || vfail=1
verify_url "$LIVE/player-simulator" || vfail=1
verify_url "$LIVE/shots" || vfail=1
verify_status "$LIVE/api/shots" 400 || vfail=1
for f in "$STAGE"/data/*.json; do
  verify_url "$LIVE/data/$(basename "$f")?v=$NEWV" || vfail=1
done
# Everything above asks the pages.dev project domain. Nobody reads the site
# there — the reader's URL is www.rankedxi.com, and it was never checked, so a
# deploy could print "verified" while www still served the previous build
# (observed 2026-08-23: / and /npsl-rankings sat on the old token for about a
# minute after a green deploy).
#
# HTML ONLY, and deliberately so. /js, /css and /data are served
# `immutable, max-age=31536000`, so asking www for js/app.js?v=$NEWV before the
# build reaches the edge pins the OLD body under the NEW url for a year. Only
# routes marked `no-cache` in _headers are safe to ask, and only those can give
# an honest answer: /npsl-rankings and the rest of the generated tree are
# max-age=300 + stale-while-revalidate, so they are *supposed* to serve the
# previous copy for a few minutes and would fail this check on a clock rather
# than on a defect. Never add an asset URL or a cached page to this list.
verify_www() {
  for i in $(seq 1 18); do          # ~90s, well past normal propagation
    curl -sfL "https://www.rankedxi.com$1" | grep -q "$NEWV" && return 0
    sleep 5
  done
  echo "DEPLOY VERIFY FAILED: www.rankedxi.com$1 still not serving v$NEWV" >&2
  return 1
}
if [ "$DEPLOY_BRANCH" = "master" ]; then
  for p in / /app; do            # the only two routes www serves DYNAMIC
    verify_www "$p" || vfail=1
  done
fi

if [ "$vfail" -ne 0 ]; then
  echo "DEPLOY VERIFY FAILED — live site disagrees with what was staged" >&2
  exit 1
fi
echo "verified: v$NEWV live on $LIVE$([ "$DEPLOY_BRANCH" = master ] && echo " and www.rankedxi.com"), $(ls "$STAGE"/data/*.json | wc -l | tr -d ' ') data files serving 200"

# Tell Bing/Yandex/Seznam what changed instead of waiting to be crawled. Google
# ignores IndexNow, so this is a cheap extra rather than a strategy, and a
# failure here must never fail a deploy that is already live and verified.
if [ -f indexnow.json ] && [ "$DEPLOY_BRANCH" = "master" ]; then
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST 'https://api.indexnow.org/indexnow' \
    -H 'Content-Type: application/json; charset=utf-8' --data @indexnow.json --max-time 20 || echo 000)
  case "$code" in
    200|202) echo "IndexNow: submitted $(python3 -c "import json;print(len(json.load(open('indexnow.json'))['urlList']))") urls (HTTP $code)" ;;
    *)       echo "IndexNow: skipped, endpoint returned HTTP $code (deploy is unaffected)" ;;
  esac
fi
