#!/usr/bin/env python3
"""Generate js/data-slim.js, the first-paint slice of js/data.js.

js/data.js is 1.1 MB raw / ~220 KB gzipped and app.js statically imports it, so
the national map could not paint until every club's crest path, socials, venue
capacity and website had been downloaded and parsed on a phone. The map and its
tooltips only read a handful of fields per club. This writes those fields (and
nothing else) into a much smaller module; app.js imports it for first paint and
fetches the full data.js after paint, merging it onto the same objects.

data.js stays the single source of truth. This file is DERIVED, never edited and
never committed (see .gitignore): deploy.sh runs `--stage` on the staged tree
right after fingerprint.py marks the staged data.js, so the slim coordinates
carry the identical keyed marks. Nothing that writes data.js needs to know it
exists. Club ORDER is preserved (array position is the legacy-URL map).

Format is columnar (one array per field) because the values compress far better
side by side than interleaved with repeated keys, and `id` is stored only where
it is not the slug of the name (most are), which alone saves ~25 KB gzipped.

  gen_slim.py                 write js/data-slim.js from js/data.js (dev, CI, tests)
  gen_slim.py --stage DIR     write DIR/js/data-slim.js from DIR/js/data.js (deploy.sh)
  gen_slim.py --check [FILE]  exit 1 unless FILE (default js/data-slim.js) matches
                              what js/data.js would generate
"""
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import _datajs  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent

# What the map, its tooltips, club-row counts and routing read before the full
# data lands. Anything not listed here arrives with data.js after first paint.
# `n` and `id` are structural (always present); the rest are optional per club.
SLIM_KEYS = ('g', 'x', 'h', 'la', 'lo', 'st', 'r', 'rr', 'acc', 'dup')
# Small constants the first screen needs verbatim. EURO_REFS, AFFIL and ROADMAP
# only feed club/about screens, which wait for the full file.
PASSTHROUGH = ('REGIONS', 'LEAGUES')

HEADER = ('/* GENERATED by scripts/gen_slim.py from js/data.js. Do not edit, do not commit.\n'
          '   First-paint slice of the club data; js/data.js (full records) loads after paint. */\n')
DECODER = (
    "const slug=n=>n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');\n"
    "const K=%s;\n"
    "export const CLUBS=D.n.map((n,i)=>{const c={n,id:D.id[i]??slug(n)};"
    "for(const k of K){const v=D[k][i];if(v!=null)c[k]=v}return c});\n"
    "for(const i in D.z)for(const k of D.z[i])CLUBS[i][k]=null;\n"
)
_D_RE = re.compile(r'^const D=(\{.*\});$', re.M)


def slug(n):
    return re.sub(r'[^a-z0-9]+', '-', n.lower()).strip('-')


def _trim(col):
    while col and col[-1] is None:
        col.pop()
    return col


def build(src):
    """Slim module source for a data.js source string."""
    clubs = _datajs.load_clubs(src)
    cols = {'n': [c['n'] for c in clubs],
            'id': _trim([None if c['id'] == slug(c['n']) else c['id'] for c in clubs])}
    for k in SLIM_KEYS:
        cols[k] = _trim([c.get(k) for c in clubs])
    # a field that is present but null (e.g. a geocode removed on purpose) is not
    # the same as absent: isFinite(null) is true, isFinite(undefined) is not.
    cols['z'] = {i: [k for k in SLIM_KEYS if k in c and c[k] is None]
                 for i, c in enumerate(clubs) if any(k in c and c[k] is None for k in SLIM_KEYS)}
    out = [HEADER]
    for name in PASSTHROUGH:
        m = re.search(r'^export const %s=.*;$' % name, src, re.M)
        if not m:
            sys.exit(f'FATAL: export const {name} not found in data.js')
        out.append(m.group(0) + '\n')
    out.append('const D=' + json.dumps(cols, ensure_ascii=False, separators=(',', ':')) + ';\n')
    out.append(DECODER % json.dumps(list(SLIM_KEYS), separators=(',', ':')))
    return ''.join(out)


def decode(slim_src):
    """Python twin of the JS decoder: the club dicts a browser would build."""
    d = json.loads(_D_RE.search(slim_src).group(1))
    clubs = []
    for i, n in enumerate(d['n']):
        c = {'n': n, 'id': (d['id'][i] if i < len(d['id']) else None) or slug(n)}
        for k in SLIM_KEYS:
            col = d[k]
            if i < len(col) and col[i] is not None:
                c[k] = col[i]
        for k in d['z'].get(str(i), ()):
            c[k] = None
        clubs.append(c)
    return clubs


def verify(slim_src, data_src):
    """Problems (empty list = good) between a slim module and the data.js it
    should mirror: same clubs in the same order, every slim field identical
    (coordinates included, so fingerprint marks must match)."""
    clubs = _datajs.load_clubs(data_src)
    got = decode(slim_src)
    if len(got) != len(clubs):
        return [f'slim has {len(got)} clubs, data.js has {len(clubs)}']
    bad = []
    for i, (g, c) in enumerate(zip(got, clubs)):
        want = {k: c[k] for k in ('n', 'id') + SLIM_KEYS if k in c}
        if g != want:
            bad.append(f'club {i} ({c.get("id")}): slim {g} != data.js {want}')
            if len(bad) >= 5:
                break
    for name in PASSTHROUGH:
        line = re.search(r'^export const %s=.*;$' % name, data_src, re.M)
        if not line or line.group(0) not in slim_src:
            bad.append(f'{name} missing or different in slim')
    return bad


def main(argv):
    if len(argv) == 3 and argv[1] == '--stage':
        stage = pathlib.Path(argv[2]) / 'js'
        src = (stage / 'data.js').read_text()
        out = build(src)
        problems = verify(out, src)
        if problems:
            sys.exit('FATAL: generated slim file disagrees with staged data.js:\n  ' + '\n  '.join(problems))
        (stage / 'data-slim.js').write_text(out)
        print(f'gen_slim: wrote {stage / "data-slim.js"} ({len(out):,} bytes)')
        return 0
    if argv[1:2] == ['--check']:
        path = pathlib.Path(argv[2]) if len(argv) > 2 else ROOT / 'js' / 'data-slim.js'
        want = build(_datajs.DATA_JS.read_text())
        if not path.exists() or path.read_text() != want:
            print(f'FAIL: {path} is missing or out of sync with js/data.js; '
                  'run python3 scripts/gen_slim.py', file=sys.stderr)
            return 1
        print(f'gen_slim: {path} in sync with js/data.js')
        return 0
    if len(argv) == 1:
        out = build(_datajs.DATA_JS.read_text())
        (ROOT / 'js' / 'data-slim.js').write_text(out)
        print(f'gen_slim: wrote js/data-slim.js ({len(out):,} bytes)')
        return 0
    sys.exit(__doc__)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
