#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — My XI accounts: schema, mail sender, secrets, merge, deploy.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

WRANGLER="npx -y wrangler@4.114.0"
D1_NAME="rankxi-signups"
PAGES_PROJECT="rank-xi"
PR_NUMBER="79"

# This script lives at <root>/scripts/, and <root> may be the myxi-accounts
# worktree (where the migration file exists before the PR is merged).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Wrangler is run from the MAIN checkout, never a worktree — invoking it from
# a worktree has bitten this project before. `git rev-parse --git-common-dir`
# points at the main repo's .git even from inside a worktree.
MAIN="$(cd "$ROOT" && cd "$(dirname "$(git rev-parse --path-format=absolute --git-common-dir)")" && pwd)"

# Local dev vars live in the main checkout and are gitignored by this branch.
ENV_FILE="$MAIN/.dev.vars"

CF_SECRETS=()

# put_pages_secret NAME VALUE — the Cloudflare equivalent of the library's
# set_secret (which targets GitHub Actions and is not what this project uses).
put_pages_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | (cd "$MAIN" && $WRANGLER pages secret put "$name" --project-name "$PAGES_PROJECT") >/dev/null 2>&1; then
    printf '  %s✓ set%s Cloudflare Pages secret %s\n' "$GREEN" "$RESET" "$name"
    CF_SECRETS+=("$name")
  else
    SKIPPED+=("Cloudflare Pages secret $name — run: $WRANGLER pages secret put $name --project-name $PAGES_PROJECT")
    warn "could not set $name — you'll need to do it by hand"
  fi
}

banner "Ranked XI — turn on My XI accounts"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this needs before anything is changed."
printf '\n'
note "main checkout : $MAIN"
note "this branch   : $ROOT"
note "local dev vars: $ENV_FILE"
printf '\n'

PREFLIGHT_OK=1
if (cd "$MAIN" && $WRANGLER whoami) >/dev/null 2>&1; then
  step "wrangler is authenticated"
else
  warn "wrangler is NOT authenticated — run: $WRANGLER login"
  PREFLIGHT_OK=0
fi

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  step "gh is authenticated"
else
  warn "gh is not authenticated — you can still merge the PR in the browser"
fi

if [[ -f "$ROOT/migrations/0003_accounts.sql" ]]; then
  step "migration 0003_accounts.sql found"
else
  warn "migrations/0003_accounts.sql is missing — are you running this from the myxi-accounts branch?"
  PREFLIGHT_OK=0
fi

printf '\n'
if [[ "$PREFLIGHT_OK" != "1" ]]; then
  warn "Fix the above, then re-run. Nothing has been changed."
  exit 1
fi
pause "All good. Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the accounts tables in D1"
say "This adds four tables — users, login_codes, sessions, user_picks — to the"
say "existing $D1_NAME database, alongside follows and hits."
printf '\n'
note "The file uses CREATE TABLE IF NOT EXISTS, so running it twice is safe."
note "It does not touch, read or modify any existing table."
printf '\n'

if confirm "Run the migration against the LIVE database now?"; then
  (cd "$MAIN" && $WRANGLER d1 execute "$D1_NAME" --remote --file="$ROOT/migrations/0003_accounts.sql")
  printf '\n'
  step "Migration applied. Verifying the tables exist:"
  printf '\n'
  (cd "$MAIN" && $WRANGLER d1 execute "$D1_NAME" --remote \
     --command="SELECT name FROM sqlite_master WHERE type='table' ORDER BY name") || true
  printf '\n'
  say "You should see: follows, hits, login_codes, sessions, user_picks, users."
else
  SKIPPED+=("D1 migration — run: $WRANGLER d1 execute $D1_NAME --remote --file=$ROOT/migrations/0003_accounts.sql")
  warn "Skipped. Accounts cannot work until this runs."
fi
printf '\n'
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Resend — create the account and add your sending domain"
say "Sign-in codes go out over an HTTPS API because Cloudflare Workers cannot"
say "open an SMTP socket. Resend is free below 3,000 emails a month."
printf '\n'
open_url "https://resend.com/signup"
step "Sign up (or log in if you already have an account)."
step "Go to Domains → Add Domain."
step "Enter a SENDING SUBDOMAIN, not the bare domain:  send.rankedxi.com"
printf '\n'
note "Why a subdomain: rankedxi.com's MX records deliver your Microsoft 365"
note "mail. A subdomain keeps this entirely separate, so nothing you do here"
note "can affect jeremy@rankedxi.com."
printf '\n'
step "Resend will now show you a set of DNS records — leave that page open."
note "The next stage is copying them into Cloudflare."
printf '\n'
ask MAIL_DOMAIN "Sending domain you entered [send.rankedxi.com]:"
[[ -z "$MAIL_DOMAIN" ]] && MAIL_DOMAIN="send.rankedxi.com"
write_env MAIL_DOMAIN "$MAIL_DOMAIN"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — add the DNS records Resend gave you"
say "rankedxi.com's DNS moved to Cloudflare on 2026-08-20, so these go there"
say "and NOT in GoDaddy."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/rankedxi.com/dns/records"
step "Open the DNS → Records tab for rankedxi.com."
step "Add every record Resend listed for $MAIL_DOMAIN."
note "Usually a DKIM TXT, an MX and SPF TXT, and a DMARC TXT."
printf '\n'
warn "Set each new record to 'DNS only' — the GREY cloud, not orange."
note "A proxied record breaks Resend's verification."
printf '\n'
warn "Do not touch the existing MX records on the bare rankedxi.com."
note "Those deliver your Microsoft 365 mail. You are only adding records for"
note "$MAIL_DOMAIN."
printf '\n'
pause "Added them all? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Resend — wait for the domain to verify"
open_url "https://resend.com/domains"
step "Back on the Domains page, click Verify on $MAIL_DOMAIN."
step "Wait for the status to read 'Verified'."
note "Usually under a minute, but DNS can take longer."
printf '\n'
note "If it stays pending: the usual causes are an orange (proxied) record, or"
note "Cloudflare appending the zone name twice — check for a record that reads"
note "send.rankedxi.com.rankedxi.com and fix the name field."
printf '\n'
pause "Showing 'Verified'? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Resend — create the API key"
open_url "https://resend.com/api-keys"
step "Click 'Create API Key'."
step "Name it something like 'rankedxi-pages'."
step "Set Permission to 'Sending access' — it never needs full access."
step "Copy the key. Resend shows it exactly once."
printf '\n'
ask_secret RESEND_API_KEY "Paste the API key (hidden):"
if [[ -z "$RESEND_API_KEY" ]]; then
  warn "No key entered — sign-in will report that it is not switched on yet."
  SKIPPED+=("RESEND_API_KEY was never set")
else
  write_env RESEND_API_KEY "$RESEND_API_KEY"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Choose the From address"
say "This must be an address on the domain you just verified, or Resend will"
say "reject every send."
printf '\n'
note "Recommended:  Ranked XI <no-reply@$MAIL_DOMAIN>"
printf '\n'
ask MAIL_FROM "From address [Ranked XI <no-reply@$MAIL_DOMAIN>]:"
[[ -z "$MAIL_FROM" ]] && MAIL_FROM="Ranked XI <no-reply@$MAIL_DOMAIN>"
write_env MAIL_FROM "$MAIL_FROM"
printf '\n'
note "Also written to $ENV_FILE so 'wrangler pages dev' works locally."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Push both values to Cloudflare Pages"
say "These become environment secrets on the $PAGES_PROJECT project, which is"
say "where the deployed endpoints read them from."
printf '\n'
if [[ -n "${RESEND_API_KEY:-}" ]]; then
  put_pages_secret RESEND_API_KEY "$RESEND_API_KEY"
fi
put_pages_secret MAIL_FROM "$MAIL_FROM"
printf '\n'
step "Confirming what the project now holds:"
printf '\n'
(cd "$MAIN" && $WRANGLER pages secret list --project-name "$PAGES_PROJECT") || true
printf '\n'
pause "Press Enter to continue."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Merge the pull request"
say "The code is on the myxi-accounts branch. deploy.sh ships whatever is in"
say "the main checkout on master, so the PR has to land first."
printf '\n'
open_url "https://github.com/jkientz-pixel/pyramid-app/pull/$PR_NUMBER"
step "Click 'Ready for review' (it is currently a draft), then 'Merge'."
printf '\n'
note "Merging in the browser rather than from here on purpose: this is the one"
note "irreversible step, and it should be your click."
printf '\n'
pause "Merged? Press Enter and I'll pull it into the main checkout."
printf '\n'

if (cd "$MAIN" && git checkout master && git pull --ff-only); then
  step "Main checkout is on master and up to date."
  if [[ -f "$MAIN/js/account.js" ]]; then
    step "Verified: js/account.js is present on master."
  else
    warn "js/account.js is NOT on master — the merge may not have landed."
    SKIPPED+=("Confirm PR #$PR_NUMBER merged, then re-run from stage 9")
  fi
else
  warn "Could not update the main checkout automatically."
  note "This project keeps many worktrees, which can block a checkout."
  note "Fix by hand in $MAIN, then continue."
  SKIPPED+=("Get $MAIN onto an up-to-date master before deploying")
fi
printf '\n'
pause "Press Enter to continue."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Deploy"
say "deploy.sh stamps a fresh cache-bust token, regenerates the SEO pages and"
say "share cards, runs preflight, commits the token bump, pushes, and deploys"
say "to Cloudflare Pages."
printf '\n'
note "It takes a few minutes. Let it finish — a half-run deploy leaves the"
note "version token inconsistent and the next run refuses to start."
printf '\n'
if confirm "Deploy to production now?"; then
  printf '\n'
  (cd "$MAIN" && ./deploy.sh)
  printf '\n'
  step "Deploy finished."
else
  SKIPPED+=("Deploy — run: cd $MAIN && ./deploy.sh")
  warn "Skipped. Nothing is live until you run it."
fi
printf '\n'
pause "Press Enter for the summary."

finish

# The library's summary covers .env writes; these are this wizard's own.
if (( ${#CF_SECRETS[@]} )); then
  printf '  %s%s%s\n' "$DIM" "Cloudflare Pages secrets set: ${CF_SECRETS[*]}" "$RESET"
fi
printf '\n'
printf '  %s%sCheck it works%s\n' "$BOLD" "$BLUE" "$RESET"
printf '  %s1.%s Open https://www.rankedxi.com/app#/myxi and follow a club.\n' "$BLUE" "$RESET"
printf '  %s2.%s Tap "Save my XI", enter your email, tick 13+, submit.\n' "$BLUE" "$RESET"
printf '  %s3.%s The code should arrive within seconds. Enter it.\n' "$BLUE" "$RESET"
printf '  %s4.%s The panel should read "Saved to <your address>".\n' "$BLUE" "$RESET"
printf '  %s5.%s Open the same page on your phone, sign in, and the club should\n' "$BLUE" "$RESET"
printf '     be there.\n'
printf '\n'
printf '  %sIf a code never arrives, ACCOUNTS-SETUP.md has the three usual causes.%s\n' "$DIM" "$RESET"
printf '  %sTo see what is stored:%s\n' "$DIM" "$RESET"
printf '  %s  %s d1 execute %s --remote \\%s\n' "$DIM" "$WRANGLER" "$D1_NAME" "$RESET"
printf '  %s    --command="SELECT u.email, p.payload, p.updated FROM users u LEFT JOIN user_picks p ON p.user_id = u.id"%s\n' "$DIM" "$RESET"
printf '\n'
